---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ../../
        target: /data
    environment:
      - FOUNDRY_USERNAME=${FOUNDRY_USER}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASS}
      - FOUNDRY_LICENSE_KEY=${FOUNDRY_LICENSE_KEY}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
